db.url=${DB_URL:jdbc:h2:mem:civicfix_db;DB_CLOSE_DELAY=-1;MODE=MySQL}
db.username=${DB_USER:sa}
db.password=${DB_PASSWORD:}
db.driver=${DB_DRIVER:org.h2.Driver}

hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
